"""empty message

Revision ID: 6be7218c4165
Revises: None
Create Date: 2018-12-12 15:00:20.220557

"""

# revision identifiers, used by Alembic.
revision = '6be7218c4165'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=164), nullable=True),
    sa.Column('school', sa.String(length=164), nullable=True),
    sa.Column('research_direction', sa.String(length=164), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('photo', sa.String(length=164), nullable=True),
    sa.Column('sex', sa.String(length=32), nullable=True),
    sa.Column('birth', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teachers_name'), 'teachers', ['name'], unique=False)
    op.create_index(op.f('ix_teachers_research_direction'), 'teachers', ['research_direction'], unique=False)
    op.create_index(op.f('ix_teachers_school'), 'teachers', ['school'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=164), nullable=True),
    sa.Column('password_hash', sa.String(length=164), nullable=True),
    sa.Column('school', sa.String(length=164), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teachers_school'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_research_direction'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_name'), table_name='teachers')
    op.drop_table('teachers')
    # ### end Alembic commands ###
